language: java
script: ant main

deploy:
  provider: releases
  file: "dist/Calculator.jar"
  skip_cleanup: true
  file_glob: true
  on:
    repo: zkwinkle/java-ci-pipeline
    branch: master
  name: $YOUR_RELEASE_NAME
  body: $YOUR_RELEASE_CONTENT