language: java
before_script:
  - sudo apt-get install ant-optional
script: ant all #&& java test/cr/ac/itcr/CalculatorTest test

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_KEY"
  file: "dist/Calculator.jar"
  skip_cleanup: true
  on:
    branch: main